### ISSUE TITLE
classTime field is being incremented each session

### ISSUE THREAD

**Issue by tomoakley** [ourparks/opendata#1]
Your `classTime` is always off the hour by a few minutes, and gets incrementally more for each item. An example:

```
"id": "96",
...
"classTime": "11:03:00"
```

```
"id": "107",
...
"classTime": "11:06:00"
```

```
"id": "163",
...
"classTime": "07:07:00"
```

```
"id": "176",
...
"classTime": "06:10:00"
```

and so on. On the session websites, the time is always correctly stated (11:03:00 is shown as 11:00:00).

**Comment by nickevansuk** [comment]
This has been resolved
