### ISSUE TITLE
Explicitly state UTC or timezone in session occurrences

### ISSUE THREAD

**Issue by tomoakley** [ourparks/opendata#4]
Hi,

In your endpoint you're not stating a timezone, or UTC. Per the OpenActive standards, you should be using the ISO 8601 standard and ideally stating the time in UTC (append a `Z` to the end of the timestamp. So if your current timestamp is `2017-07-17T19:30:00` (BST/UTC+1 time), the UTC timestamp would be `2017-07-17T18:30:00Z`. However, if the session was in a non-BST, the time would not change as non-BST is simply UTC.

Thanks!

**Comment by domfennell** [comment]
Hi @BornBarikor,

Hope you had a good weekend. Do you know if any progress has been made with this timezone issue raised by @tomoakley?

Best,

Dom

**Comment by nickevansuk** [comment]
This has now been resolved by conforming to the latest specifications.
