### ISSUE TITLE
Sessions potentially being lost between pages

### ISSUE THREAD

**Issue by house92** [ourparks/opendata#5]
I found it possible to walk the entire RPDE feed without finding a specific session, even though this could be found by artificially constructing a URL to retrieve it. Is it possible that the feed isn't reliably providing all Our Parks sessions?

**Comment by domfennell** [comment]
Hi @BornBarikor, just bringing this to your attention. Hopefully one of your developers can help.

**Comment by nickevansuk** [comment]
This should now be resolved by the fixed RPDE query. Please open a new issue if this persists.
